/* eslint-disable react/no-unescaped-entities */
import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import { InferGetStaticPropsType } from 'next';
import { WithUrqlProps, initUrqlClient } from 'next-urql';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { useQuery } from 'urql';
import profileImage from '../assets/my_profile.png';
import { AppProvider } from '../components/contexts/appContext';
import { Header } from '../components/header';
import { Layout } from '../components/layout';
import {
	HomePageInitialDocument,
	HomePageInitialQueryVariables,
	HomePagePostsDocument,
	HomePagePostsQueryVariables,
} from '../generated/graphql';
import { createHeaders, createSSRExchange, getUrqlClientConfig } from '../lib/api/client';

import PublicationFooter from '../components/publication-footer';
import { resizeImage } from '../utils/image';

const REVALIDATION_INTERVAL_POST_VIEWS_ACTIVE = 60 * 60; // 1 hour
const REVALIDATION_INTERVAL = 60 * 60 * 24 * 30; // 1 month

const NoPostsImage = ({ alt = '' }) => {
	return (
		<Image
			alt={alt}
			height={500}
			width={500}
			src={resizeImage(
				'https://cdn.hashnode.com/res/hashnode/image/upload/v1625676910594/d1jtXmfQC.png?auto=compress',
				{ h: 800, w: 800, c: 'thumb' },
			)}
		/>
	);
};

export default function Index(
	props: InferGetStaticPropsType<typeof getStaticProps> & Required<WithUrqlProps>,
) {
	const { host, publication, initialLimit } = props;

	const ssrCache = createSSRExchange();
	const urqlClient = initUrqlClient(getUrqlClientConfig(ssrCache), false); // TODO: Check why is urqlClient not automatically being passed in props. Ideally, since we are using WithUrqlClient HOC, it should automatically come

	const [fetching, setFetching] = useState(false);

	const { author, preferences, pinnedPost } = publication;
	const dynamicLimit = preferences.layout === 'magazine' ? 12 : 6;

	const [{ data }] = useQuery({
		query: HomePagePostsDocument,
		variables: { host, first: initialLimit, filter: { excludePinnedPost: !!pinnedPost } },
	});

	const { posts } = data?.publication!;

	const fetchedOnce = posts.edges.length > initialLimit;

	const postsToBeRendered = {
		edges: pinnedPost
			? [{ node: pinnedPost, cursor: `${pinnedPost.id}_${pinnedPost.publishedAt}` }].concat(
					posts.edges,
			  )
			: posts.edges,
		pageInfo: posts.pageInfo,
	};

	const fetchMore = async () => {
		setFetching(true);
		await urqlClient
			.query(HomePagePostsDocument, {
				host,
				first: dynamicLimit,
				after: posts.pageInfo.endCursor,
				filter: { excludePinnedPost: !!pinnedPost },
			})
			.toPromise()
			.finally(() => {
				setFetching(false);
			});
	};

	return (
		<AppProvider publication={publication}>
			<Layout>
				<Head>
					<title>
						{publication.displayTitle || publication.title || 'Hashnode Blog Starter Kit'}
					</title>
					<meta
						name="description"
						content={
							publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`
						}
					/>
					<meta property="twitter:card" content="summary_large_image" />
					<meta
						property="twitter:title"
						content={publication.displayTitle || publication.title || 'Hashnode Blog Starter Kit'}
					/>
					<meta
						property="twitter:description"
						content={
							publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`
						}
					/>
					<meta
						property="og:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<meta
						property="twitter:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{
							__html: JSON.stringify(addPublicationJsonLd(publication)),
						}}
					/>
				</Head>
				<Header isHome={false} />
				<div className="flex flex-col items-center">
					<section className="my-8 w-full max-w-7xl md:my-16">
						<div className="grid grid-cols-6">
							<div className="col-span-4 flex flex-col justify-center  p-4">
								<p className="">
									Hi, I'm Saket, a Full Stack Web Developer specializing in crafting stunning,
									interactive web experiences.
								</p>
								<div>open to hire</div>
								<ul className="my-4 flex list-none space-x-2">
									<a
										href="https://github.com/saketverma-03"
										target="_blank"
										className="flex w-fit items-center gap-2 rounded-lg bg-zinc-100 px-4 py-2 transition-colors hover:bg-black hover:text-white"
									>
										<svg
											xmlns="http://www.w3.org/2000/svg"
											width="16"
											height="16"
											viewBox="0 0 24 24"
											fill="none"
											stroke="currentColor"
											stroke-width="2"
											stroke-linecap="round"
											stroke-linejoin="round"
											className="lucide lucide-github"
										>
											<path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
											<path d="M9 18c-4.51 2-5-2-7-2" />
										</svg>
										Github
									</a>
									<a
										href="https://www.linkedin.com/in/saket-verma-frontend"
										target="_blank"
										className="flex w-fit items-center gap-2 rounded-lg bg-zinc-100 px-4 py-2 hover:bg-blue-500 hover:text-white"
									>
										<svg
											xmlns="http://www.w3.org/2000/svg"
											width="16"
											height="16"
											viewBox="0 0 24 24"
											fill="none"
											stroke="currentColor"
											stroke-width="1.5"
											stroke-linecap="round"
											stroke-linejoin="round"
											class="lucide lucide-linkedin"
										>
											<path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
											<rect width="4" height="12" x="2" y="9" />
											<circle cx="4" cy="4" r="2" />
										</svg>
										Linkdin
									</a>
									<a
										href="https://twitter.com/theSaketVerma"
										target="_blank"
										className="flex w-fit items-center gap-2 rounded-lg bg-zinc-100 px-4 py-2 transition-colors hover:bg-black hover:text-white"
									>
										<svg
											xmlns="http://www.w3.org/2000/svg"
											width="16"
											height="16"
											fill="currentColor"
											viewBox="0 0 16 16"
										>
											<path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z" />
										</svg>
									</a>
								</ul>
								<section className="rounded-xl bg-zinc-100 p-4 shadow-sm ">
									<h2 className="font-mono font-semibold">{'<Tech stack />'}</h2>
									<div className="mt-1 flex flex-wrap gap-3 font-mono">
										<span>Reactjs</span>
										<span>Nextjs</span>
										<span>Expressjs</span>
										<span>Mongodb</span>
										<span>Tailwindcss</span>
										<span>Bun</span>
										<span>htmx</span>
									</div>
								</section>
							</div>
							<div className="col-span-2  p-4  grayscale">
								<Image src={profileImage} className="rounded-full" />
							</div>
						</div>
					</section>

					<section className="w-full max-w-7xl p-2">
						<h1 className="mb-6 text-2xl">Projects</h1>
						<div className="grid gap-4 md:grid-cols-2">
							<div className="h-40 w-full bg-gray-300">abc</div>
							<div>
								<h2>Project title</h2>
								<p>Project tedtails</p>
								<p>Tech stack</p>
							</div>
						</div>
					</section>
				</div>
				{publication ? (
					<PublicationFooter
						authorName={publication.author.name}
						title={publication.title}
						imprint={publication.imprint}
						disableFooterBranding={publication.preferences.disableFooterBranding}
						isTeam={publication.isTeam}
						logo={publication.preferences.logo}
						darkMode={publication.preferences.darkMode}
					/>
				) : null}
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps = async () => {
	const ssrCache = createSSRExchange();
	const urqlClient = initUrqlClient(getUrqlClientConfig(ssrCache), false);
	const host = process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST;
	const homePageInitialQueryVariables: HomePageInitialQueryVariables = {
		host,
	};
	const publicationInfo = await urqlClient
		.query(HomePageInitialDocument, homePageInitialQueryVariables, {
			fetchOptions: {
				headers: createHeaders({ byPassCache: false }),
			},
			requestPolicy: 'network-only',
		})
		.toPromise();

	if (publicationInfo.error) {
		console.error('Error while fetching publication info', {
			variables: homePageInitialQueryVariables,
			error: publicationInfo.error,
		});
		throw publicationInfo.error;
	}
	if (!publicationInfo.data?.publication) {
		console.error('Publication not found fetching publication info; returning 404', {
			variables: homePageInitialQueryVariables,
		});
		return {
			notFound: true,
			revalidate: REVALIDATION_INTERVAL,
		};
	}

	const { publication } = publicationInfo.data;

	const subtractValue = publication.pinnedPost ? 1 : 0;
	const initialLimit =
		publication.preferences.layout === 'magazine' ? 12 - subtractValue : 6 - subtractValue;

	const homePagePostsVariables: HomePagePostsQueryVariables = {
		host,
		first: initialLimit,
		filter: { excludePinnedPost: !!publication.pinnedPost },
	};
	const homePagePostsResponse = await urqlClient
		.query(HomePagePostsDocument, homePagePostsVariables, {
			fetchOptions: {
				headers: createHeaders({ byPassCache: false }),
			},
			requestPolicy: 'network-only',
		})
		.toPromise();
	if (homePagePostsResponse.error) {
		console.error('Error while fetching home page posts', {
			error: homePagePostsResponse.error,
			variables: homePagePostsVariables,
		});
		throw homePagePostsResponse.error;
	}
	if (!homePagePostsResponse.data?.publication) {
		console.error('Publication not found fetching home page posts; returning 404', {
			variables: homePagePostsVariables,
		});
		return {
			notFound: true,
			revalidate: REVALIDATION_INTERVAL,
		};
	}

	return {
		props: {
			publication,
			initialLimit,
			urqlState: ssrCache.extractData(),
			host,
			isHome: true,
		},
		revalidate: 1,
	};
};
